name       : perl-file-temp
version    : '0.2311'
release    : 10
source     :
    - https://cpan.metacpan.org/authors/id/E/ET/ETHER/File-Temp-0.2311.tar.gz : 2290d61bf5c39882fc3311da9ce1c7f42dbdf825ae169e552c59fe4598b36f4a
homepage   : https://metacpan.org/pod/File::Temp
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : File::Temp can be used to create and open temporary files in a safe way
description: |
    File::Temp can be used to create and open temporary files in a safe way. There is both a function interface and an object-oriented interface. The File::Temp constructor or the tempfile() function can be used to return the name and the open filehandle of a temporary file. The tempdir() function can be used to create a temporary directory.
builddeps  :
    - perl-pod-coverage
    - perl-sub-name
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
