name       : perl-file-temp
version    : '0.2308'
release    : 5
source     :
    - https://cpan.metacpan.org/authors/id/E/ET/ETHER/File-Temp-0.2308.tar.gz : 1ca1cb22e2ab1592e864b17c861113b5960e54d398726befc90559fb8df8d1d4
license    : Artistic-1.0-Perl
component  : programming.perl
homepage   : https://github.com/Perl-Toolchain-Gang/File-Temp
summary    : File::Temp can be used to create and open temporary files in a safe way
description: |
    File::Temp can be used to create and open temporary files in a safe way
builddeps  :
    - perl-pod-coverage
    - perl-sub-name
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
